ORDEM_RISCO = {
    "RISCO_BAIXO": "BAIXO",
    "RISCO_MEDIO": "MÉDIO",
    "RISCO_ALTO": "ALTO",
    "RISCO_CRITICO": "CRÍTICO"
}

COR_CRITICO = "#FF0000"
COR_ALTO = "#FFA500"
COR_MEDIO = "#FFFF00"
COR_BAIXO = "#05EB0CB0"

BG_CRITICO = "#FF0000"
BG_ALTO = "#FFA500"
BG_MEDIO = "#FFFF00"
BG_BAIXO = "#05EB0CB0"